# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.hostname = "openstack"
  config.vm.network :private_network, :ip => "192.168.121.16"
  #config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.synced_folder "../workspace", "/data/workspace", type: "nfs", nfs_version: 4, nfs_udp: false

  config.vm.provider :libvirt do |libvirt|
     libvirt.memory = 4096
     libvirt.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    /vagrant/install.sh
  SHELL
end

